apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  annotations:
    kubernetes.io/change-cause: "Initional deployment of the app"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: myformulak8s
      labels:
        env: prod
        app: api
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: mrdev1020/kubernetes_api:v1
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80

---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: api-port
      protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer